models/User.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * Class User
 * @package app\models
 * @property integer $id
 * @property string $userCode
 * @property string $password
 * @property string $email
 * @property boolean $isLocked
 * @property integer $organizationId
 * @property string $workChargeId
 * @property integer $roleId
 * @property string $phone
 * @property string $status
 * @property string $token
 * @property string $tokenCreateAt
 * @property integer $attemptCount
 * @property integer $isDeleted
 * @property string $createdAt
 * @property string $updatedAt
 * @property string $userName
 * @property integer $kyotenType
 * @property string $companyCode
 * @property string $imei
 * @property string $supportStartAt
 * @property string $supportEndAt
 */

class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    public $authKey;
    public $accessToken;

    public static function tableName()
    {
        return 'user';
    }

    public function rules()
    {
        return [
            [['userCode', 'password'], 'required'],
        ];
    }
    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['token' => $token]);
    }

    /**
     * Finds user by email
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUserCode($userCode)
    {
        return static::findOne(['userCode' => $userCode]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return password_verify($password, $this->password);
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'createdAt',
                'updatedAtAttribute' => 'updatedAt',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

}

controllers/SettingPasswordController.php
<?php


namespace app\controllers;


use app\models\SettingPasswordForm;
use app\models\User;
use Yii;
use yii\base\Security;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

class SettingPasswordController extends Controller
{
    public $layout = 'main-login';
    //setting password

    /**
     * @param $token
     * @return string
     */
    public function actionIndex($token){
        /** @var User $user */
        $user = User::findOne(['token' => $token]);
        if($user && (strtotime($user->tokenCreateAt)+3600) >= strtotime('now')) {
            $model = new SettingPasswordForm();
            if($model->load(Yii::$app->request->post()) && $model->validate()){
                Yii::$app->session->setFlash('success','Validate Success');
            }
            return $this->render('setting-password',['model' => $model,'userCode' => $user->userCode]);
        }
        return $this->render('expired-registration');

    }

    /**
     * @return bool
     * @throws \yii\base\Exception
     */
    public function actionSendEmail(){
        if(Yii::$app->request->isAjax ){
            $userCode = Yii::$app->request->get('userCode','');
            $user = User::findByUserCode($userCode);
            if($user){
                if($user->token == '' || (strtotime($user->tokenCreateAt) + 3600) < strtotime('now') ){
                    $user->token = Yii::$app->security->generateRandomString() . '_' . time();
                    $user->tokenCreateAt = date('Y-m-d H:i:s');
                    if(!$user->save()){
                        return false;
                    }
                }
                return Yii::$app->mailer->compose('template-mail',['user' => $user])
                    ->setFrom('admin@example.com')
                    ->setTo($user->email)
                    ->setSubject(Yii::t('app','Email Subject'))
                    ->send();
            }
        }


    }

    /**
     * @param $userCode
     * @return bool|string
     * @throws \Throwable
     * @throws \yii\base\Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionChangePassword($userCode){
        Yii::$app->response->format = 'json';
        if(Yii::$app->request->isAjax){
            $user = User::findByUserCode($userCode);
            if($user){
                $canSave = (strtotime($user->tokenCreateAt)+3600) >= strtotime('now');
                if(!$canSave){
                    return $this->render('expired-registration');
                }
                $user->password = Yii::$app->request->post('password','');
                if($user->validate('password')){
                    $user->isLocked = 0;
                    $user->attemptCount = 0;
                    $user->token = '';
                    $user->tokenCreateAt  = 0;
                    $user->password = Yii::$app->security->generatePasswordHash(Yii::$app->request->post('password'));
                    if($user->update()){
                        return true;

                    }
                }
            }
        }
        return false;
    }

    public function actionExpiredRegistration(){
        return $this->render('expired-registration');
    }
}

controllers/UserController.php
<?php


namespace app\controllers;

use app\models\ResetPasswordForm;
use app\models\SettingPasswordForm;
use app\models\User;
use Yii;

use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;

class UserController extends Controller
{
    public $layout = 'main-login';

    /**
     * @return array|string
     */
    public function actionResetPassword(){
        $model = new ResetPasswordForm;
        if($model->load(Yii::$app->request->post()) &&  $model->validate()){
            if($model->validateUser()){
                Yii::$app->session->setFlash('success','Success');
            }
        }
        return $this->render('reset-password',['model' =>$model]);
    }


    public function actionTest(){
        $pwd = 'AAAAFT1000020?$';
        $password = str_split($pwd);
        $isNumber = $isLowerCase = $isUpperCase = $isSpecialCharacter = $hasUserCode = false;

        $userCode = 'FT1000020';

        if(stripos($pwd,$userCode)){
            $hasUserCode = true;
        }
        if(!$hasUserCode){
            $check = 0;
            foreach ($password as $character){
                if(ctype_digit($character)){
                    $isNumber = true;
                }
                else if(ctype_upper($character)){
                    $isUpperCase = true;
                }
                else if(ctype_lower($character)){
                    $isLowerCase = true;
                }
                else{
                    $isSpecialCharacter = true;
                }
                $check = $isNumber + $isUpperCase + $isLowerCase + $isSpecialCharacter;
                if($check >= 2){
                    break;
                }

            }
            if($check >= 2){
                echo 'Valid Password';
            }else{
               echo 'Invalid password';
            }
        }else{
            echo 'Password doesn\'t include userCode';
        }


    }

    public function actionTest1($userCode){
        echo $userCode;
    }




}

views/user/reset-password.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\Pjax;

$this->title = 'Reset Password';
?>

<h3 id="reset-password-title"><?= Yii::t('app','Reset Pasword page')?></h3>
<a id = 'return' href="<?= Url::to(['site/login'])?>"><i class="fa fa-arrow-left" aria-hidden="true"></i><?= Yii::t('app','Return')?></a>

<div id="reset-password-content">
    <h4 id="reset-note"><?= Yii::t('app','Please enter user code and choose verify email')?></h4>
    <?php $form = ActiveForm::begin(
            [
                'id' => 'reset-password-form',
            ]
    )?>
        <label for="userCode"><?= Yii::t('app','User code')?></label>
        <?= $form->field($model, 'userCode',['template' => "<div style='display: flex;'><i class=\"fa fa-user icon\"></i>{input}</div>\n<div>{error}</div>"])->textInput(['id'=>'reset-userCode']) ?>
       <div id="button-group">
           <?= Html::submitButton(Yii::t('app','Verify email'),['class' => 'btn btn-primary','id' => 'btn-verify-email'])?>
       </div>
    <?php ActiveForm::end()?>
</div>

<!--Confirm send mail modal-->
<?php
Modal::begin([
    'header' =>  Yii::t('app','Confirm send email'),
    'id' => 'send-mail-modal',
    'closeButton' => false,
]);
?>
<div class="modal-body">
        <div id="confirm-message">
            <p><?= Yii::t('app','Would you like sending mail with this user code?')?></p>
        </div>
        <div id="btn-group">
            <button class="btn btn-default" id='btn-cancel'> <?= Yii::t('app','Cancel')?></button>
            <button class="btn" id='btn-send'><?= Yii::t('app','Send')?></button>
        </div>
    </div>
<?php Modal::end(); ?>

<!--Alert check mail modal-->
<?php
Modal::begin([
    'header' =>  Yii::t('app','Send Email Notice'),
    'id' => 'check-mail-modal',
    'closeButton' => false,
]);
?>
<div class="modal-body">
    <div id="confirm-message">
        <p><?= Yii::t('app','Please check your email to reset password')?></p>
    </div>
    <div id="btn-group">
        <button class="btn btn-success" id='btn-close-mail'><?= Yii::t('app','Close')?></button>
    </div>
</div>
<?php Modal::end(); ?>

<?php $this->registerCssFile('@web/css/login.css')?>
<?php $this->registerJsFile('@web/js/reset-password.js',['depends' => 'yii\web\JqueryAsset'])?>
<script>
    var urlSendMail = "<?= Url::to(['setting-password/send-email'])?>";
    var isValidateSuccess = <?= Yii::$app->session->hasFlash('success') ? 1 : 0 ?>;
</script>