models/SettingPasswordForm.php
<?php


namespace app\models;

use Yii;
use yii\base\Model;

class SettingPasswordForm extends Model
{
    public $userCode;
    public $password;
    public $repassword;

    public function rules()
    {
        return [
            [['userCode','password'], 'required'],
            ['repassword','required','whenClient' => "function(attribute,value){
                        return $('#setting-pwd').val() != '';
                    }"
            ],
            [['repassword'], 'compare', 'compareAttribute' => 'password', 'whenClient' => "function(attribute,value){
                        var password = $('#setting-pwd').val();
                        var repassword = $('#setting-re-pwd').val();
                        return password != '' && repassword != '';
                    
                    }"
            ],
            ['password','string','min' => 8,'max' => 16,'when' => function($model){
                           return $model->password != '';
                    },
                'enableClientValidation' => false,
            ],
            ['password','validatePassword']
        ];
    }

    public function validatePassword($attribute,$params){
        $password = str_split($this->$attribute);
        $isNumber = $isLowerCase = $isUpperCase = $isSpecialCharacter = $hasUserCode = false;
        if(stripos($this->$attribute,$this->userCode)){
            $hasUserCode = true;
        }

        if(!$hasUserCode){
            $check = 0;
            foreach ($password as $character){
                if(ctype_digit($character)){
                    $isNumber = true;
                }
                else if(ctype_upper($character)){
                    $isUpperCase = true;
                }
                else if(ctype_lower($character)){
                    $isLowerCase = true;
                }
                else{
                    $isSpecialCharacter = true;
                }
                $check = $isNumber + $isUpperCase + $isLowerCase + $isSpecialCharacter;
                if ($check >= 2){
                    break;
                }

            }
            if($check >= 2){
                Yii::$app->session->setFlash('sucess','Validate Success');
            }else{
                $this->addError('server-error',Yii::t('app','Password include more than 2 types character such as: number and upper case alphabet or lower case alphabet,etc,... '));
            }
        }else{
            $this->addError('server-error',Yii::t('app','Not using usercode for password'));
        }


    }

}

controllers/SettingPasswordController.php
<?php


namespace app\controllers;


use app\models\SettingPasswordForm;
use app\models\User;
use Yii;
use yii\base\Security;
use yii\web\Controller;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

class SettingPasswordController extends Controller
{
    public $layout = 'main-login';
    //setting password

    /**
     * @param $token
     * @return string
     */
    public function actionIndex($token){
        /** @var User $user */
        $user = User::findOne(['token' => $token]);
        if($user && (strtotime($user->tokenCreateAt)+3600) >= strtotime('now')) {
            $model = new SettingPasswordForm();
            if($model->load(Yii::$app->request->post()) && $model->validate()){
                Yii::$app->session->setFlash('success','Validate Success');
            }
            return $this->render('setting-password',['model' => $model,'userCode' => $user->userCode]);
        }
        return $this->render('expired-registration');

    }

    /**
     * @return bool
     * @throws \yii\base\Exception
     */
    public function actionSendEmail(){
        if(Yii::$app->request->isAjax ){
            $userCode = Yii::$app->request->get('userCode','');
            $user = User::findByUserCode($userCode);
            if($user){
                if($user->token == '' || (strtotime($user->tokenCreateAt) + 3600) < strtotime('now') ){
                    $user->token = Yii::$app->security->generateRandomString() . '_' . time();
                    $user->tokenCreateAt = date('Y-m-d H:i:s');
                    if(!$user->save()){
                        return false;
                    }
                }
                return Yii::$app->mailer->compose('template-mail',['user' => $user])
                    ->setFrom('admin@example.com')
                    ->setTo($user->email)
                    ->setSubject(Yii::t('app','Email Subject'))
                    ->send();
            }
        }


    }

    /**
     * @param $userCode
     * @return bool|string
     * @throws \Throwable
     * @throws \yii\base\Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionChangePassword($userCode){
        Yii::$app->response->format = 'json';
        if(Yii::$app->request->isAjax){
            $user = User::findByUserCode($userCode);
            if($user){
                $canSave = (strtotime($user->tokenCreateAt)+3600) >= strtotime('now');
                if(!$canSave){
                    return $this->render('expired-registration');
                }
                $user->password = Yii::$app->request->post('password','');
                if($user->validate('password')){
                    $user->isLocked = 0;
                    $user->attemptCount = 0;
                    $user->token = '';
                    $user->tokenCreateAt  = 0;
                    $user->password = Yii::$app->security->generatePasswordHash(Yii::$app->request->post('password'));
                    if($user->update()){
                        return true;

                    }
                }
            }
        }
        return false;
    }

    public function actionExpiredRegistration(){
        return $this->render('expired-registration');
    }
}

views/setting-password/expired-registration.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
?>
<div id="expired-registration-content">
    <p><?= Yii::t('app','Registration link has expired')?></p>
    <p><?= Yii::t('app','Time out is one hour')?></p>
    <p><?= Yii::t('app','Please visit login page to setting new password')?></p>
    <div id="btn-group" style="margin:80px auto">
        <a href="<?= Url::to(['site/login'])?>" class="btn btn-info" style="width: 160px;"><?= Yii::t('app','Login')?></a>
    </div>

</div>

<?php $this->registerCssFile('@web/css/login.css')?>

views/setting-password/setting-password.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
/** @var string $userCode */
$show = Yii::t('app', 'Show');
$passwordLabel = Yii::t('app','New password');
$repasswordLabel = Yii::t('app','Re-password');
?>
<div>
    <h3><?= Yii::t('app','Setting Password') ?></h3>
    <div id="reset-password-content">
        <div class="alert alert-info">
            <p style="font-size: 24px;font-weight: 700;"><?= Yii::t('app','Note setting password')?></p>
            <ul>
                <li><?= Yii::t('app','Password length: 8-16')?></li>
                <li><?= Yii::t('app','Password includes more than 2 types such as alphabet and number,etc,..')?></li>
                <li><?= Yii::t('app','Do not use password includes the same characters such as 0000,1234,abcd')?></li>
                <li><?= Yii::t('app','Do not allow password including user code')?></li>
            </ul>
        </div>

        <?php $form = ActiveForm::begin(
                [
                     'id' => 'setting-password-form',
                ]
        )?>

            <div class="form-group" style="margin-bottom:5px;">
                <label for="userCode" class='setting-pwd-label'><?= Yii::t('app','User code')?></label>
                <span style="margin-left:-32px;font-weight: 700"><?= $userCode ?></span>
            </div>

            <?= $form->field($model, 'password',['template' => "<div style='display: flex;'><label for=\"new-password\" class='setting-pwd-label'>$passwordLabel</label>{input}<span id='toggle-password' class='password-mask'>{$show}</span></div>\n<div class='custom-error'>{error}</div>"])->passwordInput(['id'=>'setting-pwd']) ?>

            <?= $form->field($model, 'repassword',['template' => "<div style='display: flex;'><label for=\"re-password\"  class='setting-pwd-label'>$repasswordLabel</label>{input}<span id='toggle-password' class='password-mask'>{$show}</span></div>\n<div class='custom-error'>{error}</div>"])->passwordInput(['id'=>'setting-re-pwd']) ?>

            <?= $form->field($model, 'userCode')->hiddenInput(['value' => $userCode])->label(false) ?>

            <?php if($model->hasErrors('server-error')){?>
                <p class="custom-error"><?= $model->getFirstError('server-error')?></p>

            <?php }?>

            <div id="button-group">
                <?= Html::submitButton(Yii::t('app','Register'),['class' => 'btn btn-primary','id' => 'btn-register-pwd'])?>
            </div>

        <?php ActiveForm::end()?>
    </div>
    <!--Confirm send mail modal-->
    <?php
    Modal::begin([
        'header' =>  Yii::t('app','Confirm change password'),
        'id' => 'confirm-change-pwd-modal',
        'closeButton' => false,
    ]);
    ?>
    <div class="modal-body">
        <div id="confirm-message">
            <p><?= Yii::t('app','Password will change. Please confirm it?')?></p>
        </div>
        <div id="btn-group">
            <button class="btn btn-default" id='btn-change-cancel'> <?= Yii::t('app','Cancel')?></button>
            <button class="btn" id='btn-change-pwd'><?= Yii::t('app','Yes')?></button>
        </div>
    </div>
    <?php Modal::end(); ?>

    <!--Confirm send mail modal-->
    <?php
    Modal::begin([
        'header' =>  Yii::t('app','Change password notice'),
        'id' => 'change-pwd-notice',
        'closeButton' => false,
    ]);
    ?>
    <div class="modal-body">
        <div id="confirm-message">
            <p><?= Yii::t('app','Changing password completed. You can login now')?></p>
        </div>
        <div id="btn-group">
            <button class="btn btn-success" id='btn-login'><?= Yii::t('app','Login')?></button>
        </div>
    </div>
    <?php Modal::end(); ?>

</div>
<script>
    var validateSettingForm = "<?= Yii::$app->session->hasFlash('success') ? 1 : 0 ?>";
    var urlChangePassword = "<?= Url::to(['setting-password/change-password','userCode' => $userCode])?>";
    var urlLogin = "<?= Url::to(['site/login'])?>";
    var hide = "<?= Yii::t('app','Hide')?>";
    var show = "<?= Yii::t('app','Show')?>";
    var csrf = "<?= Yii::$app->request->csrfToken; ?>";
</script>
<?php $this->registerCssFile('@web/css/login.css')?>
<?php $this->registerJsFile('@web/js/setting-password.js',['depends' => 'yii\web\JqueryAsset'])?>